Reisikulud/Reisikulud/Models/Travel.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reisikulud.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Travel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Travel()
        {
            this.Expenses = new HashSet<Expense>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public int PersonId { get; set; }
        public string Goal { get; set; }
        public int Category { get; set; }

        [DisplayFormat(ApplyFormatInEditMode =true, DataFormatString ="{0:dd.MM.yyyy}")]
        public Nullable<System.DateTime> StartDate { get; set; }
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:dd.MM.yyyy}")]
        public Nullable<System.DateTime> EndDate { get; set; }
        public int State { get; set; }
        public Nullable<int> PictureId { get; set; }
    
        public virtual DataFile DataFile { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Expense> Expenses { get; set; }
        public virtual Person Person { get; set; }
    }
}

Reisikulud/Reisikulud/Controllers/DataFilesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Reisikulud.Models;
using System.IO;

namespace Reisikulud.Controllers

{
    //[Authorize(Roles = "Raamatupidaja")]
    public class DataFilesController : Controller


    {

        private BackSeatEntities db = new BackSeatEntities();

        [OutputCache(VaryByParam = "id", Location = System.Web.UI.OutputCacheLocation.ServerAndClient, Duration = 3600)] //failid jäetakse minu masinas natuke aega meelde, lehe laadimine läheb kiiremini
        public ActionResult Content(int id)
        {
            DataFile file = db.DataFiles.Find(id);
            if (file == null) return HttpNotFound();
            byte[] buff = file.Content;
            return File(buff, file.ContentType);

        }
        //[Authorize(Roles = "Raamatupidaja")]
        // GET: DataFiles
        public ActionResult Index()
        {
            return View(db.DataFiles.ToList());
        }
        
        // GET: DataFiles/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DataFile dataFile = db.DataFiles.Find(id);
            if (dataFile == null)
            {
                return HttpNotFound();
            }
            return View(dataFile);
        }
        
        // GET: DataFiles/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: DataFiles/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Name,ContentType")] DataFile dataFile, HttpPostedFileBase file)
        {
            if (file == null) return View(dataFile); //saan faili ja kindel et ka on fail
            if (file.ContentLength == 0) return View(dataFile);

            using (BinaryReader reader = new BinaryReader(file.InputStream))  //oskab faili sisu lugeda
            {                                                                  //using hoiab loetut mälus kindla aja
                byte[] buff = reader.ReadBytes(file.ContentLength); //loeme faili puhvrisse

                //if (ModelState.IsValid)
                {
                    dataFile = new DataFile //sisu panen datafilesse
                    {
                        ContentType = file.ContentType,
                        Name = file.FileName.Split('\\').Last(), // Split('\\').Last() paneb ainult failinime
                        Content = buff,
                    };

                    db.DataFiles.Add(dataFile);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
            }
        }
        // GET: DataFiles/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DataFile dataFile = db.DataFiles.Find(id);
            if (dataFile == null)
            {
                return HttpNotFound();
            }
            return View(dataFile);
        }

        // POST: DataFiles/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Name,ContentType,Content")] DataFile dataFile)
        {
            if (ModelState.IsValid)
            {
                db.Entry(dataFile).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(dataFile);
        }

        // GET: DataFiles/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DataFile dataFile = db.DataFiles.Find(id);
            if (dataFile == null)
            {
                return HttpNotFound();
            }
            return View(dataFile);
        }

        // POST: DataFiles/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            DataFile dataFile = db.DataFiles.Find(id);
            db.DataFiles.Remove(dataFile);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Reisikulud/Reisikulud/Controllers/TravelsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Reisikulud.Models;
using System.IO;

namespace Reisikulud.Controllers
{
    public class TravelsController : Controller
    {
        private BackSeatEntities db = new BackSeatEntities();


        private Dictionary<int, string> Kategooriad = new Dictionary<int, string>
        {
            {0, "Määramata" },
            {1, "Transport" },
            {2, "Majutus" },
            {3, "Toitlustus" },
            {4, "Konverentsid" },
            {5, "Muud" }
        };
        private Dictionary<int, string> Staatused = new Dictionary<int, string>
        {
            {0, "Määramata" },
            {1, "Salvestatud" },
            {2, "Esitatud" },
            {3, "Kinnitatud" },
            {4, "Hüvitatud" },
        };

        // GET: Travels
        //public ActionResult Index()
        //{


        //    var travels = db.Travels.Include(t => t.DataFile).Include(t => t.Person);
        //    return View(travels.ToList());
        //}
        //[Authorize]
        //public ActionResult Index()
        //{

        //    var travels = db.Travels.Where(x => x.Person.Email == User.Identity.Name);
        //    return View(travels);

        //}

        [Authorize]
        public ActionResult Index(string sortKey = "Id", string sortDirection = "Asc", string searchString = "", DateTime? searchstartDate = null, DateTime? searchendDate = null)
        {

            //DateTime limit = DateTime.Now.AddMonths(-6);
            Person person = db.People.Where(x => x.Email == User.Identity.Name).SingleOrDefault();
            if (person == null) return RedirectToAction("Index", "Home");

            var q = db.Travels.Where(x => true)
                .Where(x => searchString == "" || x.Person.FirstName.Contains(searchString) || x.Person.LastName.Contains(searchString))
                .Where(x => !searchstartDate.HasValue || (searchstartDate >= x.StartDate && searchstartDate <= x.EndDate))
            ;

            if (User.IsInRole("Raamatupidaja")) q = q.Where(x => x.State > 0);
            else if (User.IsInRole("Osakonnajuhataja")) q = q.Where(x => x.Person.DepartmentId == person.Department.Id);
            else q = q.Where(x => x.PersonId == person.Id);



            var qs = q.OrderBy(x => x.Id).Take(20);
            
            ViewBag.SortKey = sortKey;
            ViewBag.SortDirection = sortDirection;
            ViewBag.SearchString = searchString;
            ViewBag.SearchEndDate = searchendDate;
            ViewBag.SearchStartDate = searchstartDate;
            ViewBag.Staatused = Staatused;

            switch (sortKey + sortDirection)
            {
                case "NameAsc": qs = q.OrderBy(x => x.Name); break;
                case "NameDesc": qs = q.OrderByDescending(x => x.Name); break;
                case "StateAsc": qs = q.OrderBy(x => x.State); break;
                case "StateDesc": qs = q.OrderByDescending(x => x.State); break;
                case "StartDateAsc": qs = q.OrderBy(x => x.StartDate); break;
                case "StartDateDesc": qs = q.OrderByDescending(x => x.StartDate); break;
            }

            return View(qs.ToList());
        }
        
        public ActionResult ChangeState(int id, int state)
        {
            Travel travel = db.Travels.Find(id);
            if (travel != null)
            {
                travel.State = state;
                db.SaveChanges();
            }

            return RedirectToAction("Index");
        }

        // GET: Travels/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Travel travel = db.Travels.Find(id);
            if (travel == null)
            {
                return HttpNotFound();
            }
            //ViewBag.category = new SelectList(Kategooriad, "Key", "Value");
            //ViewBag.Kategooriad = Kategooriad;

            return View(travel);
        }


        // GET: Travels/Create
        public ActionResult Create()
        {
            Person person = db.People.Where(x => x.Email == User.Identity.Name).SingleOrDefault();
            if (person == null) return RedirectToAction("Index");


            ViewBag.PersonId = new SelectList(db.People, "Id", "FullName", person.Id);
            return View(new Travel { State = 1, PersonId = person.Id, PictureId = null, StartDate = DateTime.Now, EndDate = DateTime.Now.AddDays(7), Category = 0 });
        }

        // POST: Travels/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Name,Description,PersonId,Goal,Category,StartDate,EndDate,State,PictureId")] Travel travel)
        {
            if (ModelState.IsValid)
            {
                if (travel.StartDate == null) travel.StartDate = DateTime.Now;
                db.Travels.Add(travel);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.PictureId = new SelectList(db.DataFiles, "Id", "Name", travel.PictureId);
            ViewBag.PersonId = new SelectList(db.People, "Id", "FirstName", travel.PersonId);
            return View(travel);
        }

        public ActionResult AddExpense(int id, string name, decimal cost, int duration, string description, int category)
        {
            Travel travel = db.Travels.Find(id);
            if (travel != null)
            {
                try
                {
                    travel.Expenses.Add(new Expense
                    {
                        Name = name,
                        Cost = cost,
                        Duration = duration,
                        Description = description,
                        Category = category
                    }
                   );
                    db.SaveChanges();
                }
                catch (Exception e)
                {
                    ViewBag.Error = e.Message;
                }
            }

            return RedirectToAction("Edit", new { id });
        }
        public ActionResult RemoveExpense(int id, int expenseId)
        {
            Expense expense = db.Expenses.Find(expenseId);
            if (expense != null)
            {
                db.Expenses.Remove(expense);
                db.SaveChanges();
            }
            return RedirectToAction("Edit", new { id });
        }


        // GET: Travels/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Travel travel = db.Travels.Find(id);
            if (travel == null)
            {
                return HttpNotFound();
            }
            ViewBag.PictureId = new SelectList(db.DataFiles, "Id", "Name", travel.PictureId);
            ViewBag.PersonId = new SelectList(db.People, "Id", "FirstName", travel.PersonId);
            ViewBag.category = new SelectList(Kategooriad, "Key", "Value");
            ViewBag.Kategooriad = Kategooriad;
            return View(travel);
        }

        // POST: Travels/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Name,Description,PersonId,Goal,Category,StartDate,EndDate,State,PictureId")] Travel travel, HttpPostedFileBase file)
        {
            if (ModelState.IsValid)
            {
                db.Entry(travel).State = EntityState.Modified;
                db.SaveChanges();
                if (file != null && file.ContentLength > 0)  // file on olemas
                {
                    using (BinaryReader br = new BinaryReader(file.InputStream))
                    {
                        byte[] buff = br.ReadBytes(file.ContentLength);

                        DataFile uusFile = new DataFile
                        {
                            ContentType = file.ContentType,
                            Content = buff,
                            Name = file.FileName.Split('\\').Last()
                        };
                        db.DataFiles.Add(uusFile);
                        db.SaveChanges();
                        travel.PictureId = uusFile.Id;

                    }
                }
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.PictureId = new SelectList(db.DataFiles, "Id", "Name", travel.PictureId);
            ViewBag.PersonId = new SelectList(db.People, "Id", "FullName", travel.PersonId);
            return View(travel);
        }



        // GET: Travels/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Travel travel = db.Travels.Find(id);
            if (travel == null)
            {
                return HttpNotFound();
            }
            return View(travel);
        }

        // POST: Travels/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Travel travel = db.Travels.Find(id);
            db.Travels.Remove(travel);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

Reisikulud/Reisikulud/Views/Travels/Edit.cshtml
@model Reisikulud.Models.Travel

@{
    ViewBag.Title = "Edit";
}

<h2>Muuda</h2>


@using (Html.BeginForm("Edit", "Travels", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    @*<h4>Travel</h4>*@
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.Id)

    <div class="form-group">
        @Html.LabelFor(model => model.Name, "Nimi", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
        </div>
    </div>

    @*<div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>*@
    @Html.HiddenFor(x => Model.Description)

    <div class="form-group">
        @Html.LabelFor(model => model.PersonId, "Kasutaja", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("PersonId", null, htmlAttributes: new { @class = "form-control", disabled = "disabled" })
            @Html.ValidationMessageFor(model => model.PersonId, "", new { @class = "text-danger" })
            @Html.HiddenFor(x => Model.PersonId)
        </div>
    </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Goal, "Eesmärk", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Goal, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Goal, "", new { @class = "text-danger" })
            </div>
        </div>

        @*<div class="form-group">
                @Html.LabelFor(model => model.Category, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Category, new { htmlAttributes = new { @class = "form-control", disabled="disabled" } })
                    @Html.ValidationMessageFor(model => model.Category, "", new { @class = "text-danger" })
                </div>
            </div>*@
        @Html.HiddenFor(x => Model.Category)

        <div class="form-group">
            @Html.LabelFor(model => model.StartDate, "Reisi algus", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="date" @Html.EditorFor(model => model.StartDate, new { htmlAttributes = new { @class = "form-control", @value=Model.StartDate?.ToString("yyyy-MM-dd") } })
                       @Html.ValidationMessageFor(model => model.StartDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EndDate, "Reisi lõpp", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="date" @Html.EditorFor(model => model.EndDate, new { htmlAttributes = new { @class = "form-control", @value = Model.EndDate?.ToString("yyyy-MM-dd") } })
                        @Html.ValidationMessageFor(model => model.EndDate, "", new { @class = "text-danger" })
            </div>
        </div>

        @*<div class="form-group">
                @Html.LabelFor(model => model.State, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.State, new { htmlAttributes = new { @class = "form-control", disabled="disabled" } })
                    @Html.ValidationMessageFor(model => model.State, "", new { @class = "text-danger" })
                </div>
            </div>*@
        @Html.HiddenFor(model => model.State)

        @*<div class="form-group">
                @Html.LabelFor(model => model.PictureId, "PictureId", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("PictureId", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.PictureId, "", new { @class = "text-danger" })
                </div>
            </div>*@
        @Html.HiddenFor(model => model.PictureId)

        <div class="form-group">
            <div class="col-md-offset-1 col-md-20">
                <table>
                    <tr>
                        <td><img id="pilt" @*src='@Url.Action("Content", "Datafiles", new { id = Model.DataFile.Id })' height="80"*@ /></td>
                        <td><label class="col-md-2" for="file">Pildike:</label></td>
                        <td><input type="file" name="file" id="file" /></td>
                        @*<td><input type="submit" value="Lisa" class="btn btn-primary" /></td>*@
                    </tr>
                </table>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Salvesta" class="btn btn-primary" />
            </div>
        </div>
    </div>

    <dt>
        <strong>Reisi summa</strong>
    </dt>
    <dd>
        @Model.Expenses.Sum(x => x.Cost * (x.Category == 2 ? x.Duration : 1))
    </dd>
    <dt>
        <strong>Reisi summa + päevaraha (50€ päev)</strong>
    </dt>
    <dd>
        @Model.Expenses.Sum(x => x.Cost * (x.Category == 2 ? x.Duration : 1) + (x.Duration * 50))
    </dd>


    }
    <h2>Selle reisi kulutused</h2>
    <form action="@Url.Action("AddExpense")" method="post">
        <input type="hidden" name="id" value="@Model.Id" />
        <table class="table table-striped">
            <tr>
                <th>Nimetus</th>
                <th>Kategooria</th>
                <th>Kulutus</th>
                <th>Kestus</th>
                <th>Kirjeldus</th>
                <th> </th>
            </tr>
            @foreach (var kulu in Model.Expenses)
            {
                <tr>
                    <td>@kulu.Name</td>
                    <td>@ViewBag.Kategooriad[kulu.Category]</td>
                    <td>@kulu.Cost</td>
                    <td>@kulu.Duration</td>
                    <td>@kulu.Description</td>
                    <td>@Html.ActionLink("Eemalda", "RemoveExpense", new { id = Model.Id, expenseId = kulu.Id })</td>
                </tr>
            }
            <tr>
                <td><input type="text" name="name" /></td>
                <td>@Html.DropDownList("category", null, "-- vali --")</td>
                <td><input type="number" name="cost" /></td>
                <td><input type="number" name="duration" /></td>
                <td><input type="text" name="description" /></td>
                <td><input type="submit" value="Lisa" /></td>
            </tr>
        </table>
        <p class="text-danger">@ViewBag.Error</p>
    </form>

    <div>
        @Html.ActionLink("Tagasi", "Index")
    </div>

    @section Scripts {
        @Scripts.Render("~/bundles/jqueryval")
    }

Reisikulud/Reisikulud/Views/Travels/Index.cshtml
@model IEnumerable<Reisikulud.Models.Travel>

@{
    ViewBag.Title = "Aruanded";
}



<h2>@ViewBag.FullName Siin on mõned meie aruanded </h2>

<p>
    @Html.ActionLink("Loo uus", "Create")
</p>

<form>
    <h2><small>Otsing</small></h2>
    <input type="date" name="searchstartDate" value="@System.DateTime.Today.ToString("yyyy-MM-dd")"/>
    @*<input type="date" name="searchendDate" value="@ViewBag.SearchEndDate" />*@
    <input type="text" name="searchString" placeholder="Otsi nime järgi" value="@ViewBag.SearchString" />
    <button type="submit" class="glyphicon glyphicon-search btn btn btn-primary"></button>
    <p></p>
    <p></p>
</form>


<table class="table table-striped">
    <tr>
        <th>
            @*@Html.DisplayNameFor(model => model.Name)*@
            @Html.ActionLink("Nimi", "Index", new { sortKey = "Name", sortDirection = ((ViewBag.SortKey == "Name" && ViewBag.SortDirection == "Asc") ? "Desc" : "Asc") })
        </th>
        @*<th>
                @Html.DisplayNameFor(model => model.Description)
            </th>*@
        <th>
            Eesmärk
        </th>
        @*<th>
                @Html.DisplayNameFor(model => model.Category)
            </th>*@
        <th>
            @*@Html.DisplayNameFor(model => model.StartDate)*@
            @Html.ActionLink("Reisi algus", "Index", new { sortKey = "StartDate", sortDirection = ((ViewBag.SortKey == "Name" && ViewBag.SortDirection == "Asc") ? "Desc" : "Asc") })
        </th>
        <th>
            Reisi Lõpp
        </th>
        <th>
            @*@Html.DisplayNameFor(model => model.State)*@
            @Html.ActionLink("Staatus", "Index", new { sortKey = "State", sortDirection = ((ViewBag.SortKey == "Name" && ViewBag.SortDirection == "Asc") ? "Desc" : "Asc") })
        </th>
        <th>
            Sisu
        </th>
        <th>
            Reisija
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            @*<td>
                    @Html.DisplayFor(modelItem => item.Description)
                </td>*@
            <td>
                @Html.DisplayFor(modelItem => item.Goal)
            </td>
            @*<td>
                    @Html.DisplayFor(modelItem => item.Category)
                </td>*@
            <td>
                @Html.DisplayFor(modelItem => item.StartDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.EndDate)
            </td>
            <td>
                @if (item.State == 1)
                {
                    @Html.HiddenFor(modelItem => item.State)<div class="alert alert-info"><strong>@ViewBag.Staatused[item.State]</strong></div>
                }
                else if (item.State == 2)
                {
                    @Html.HiddenFor(modelItem => item.State)<div class="alert alert-warning"><strong>@ViewBag.Staatused[item.State]</strong></div>
                }
                else if (item.State == 3)
                {
                    @Html.HiddenFor(modelItem => item.State)<div class="alert alert-danger"><strong>@ViewBag.Staatused[item.State]</strong></div>
                }
                else
                {
                    @Html.HiddenFor(modelItem => item.State)<div class="alert alert-success"><strong>@ViewBag.Staatused[item.State]</strong></div>
                }
            </td>
            <td>
                @*@Html.DisplayFor(modelItem => item.DataFile.Content)*@
                 
                    <img class="centered-and-cropped" height="120" width="150" src="@Url.Action("Content", "DataFiles", new { id = (item.DataFile?.Id??0) })" />
                
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Person.Nimi)
            </td>
            @if ((item.State == 1) && (User.IsInRole("Tavakasutaja")) || (item.State == 1) && (item.Person.Email == User.Identity.Name))
            {
                <td>
                    @Html.ActionLink("Teave", "Details", new { id = item.Id }) |
                    @Html.ActionLink("Muuda", "Edit", new { id = item.Id }) |
                    @Html.ActionLink("Kustuta", "Delete", new { id = item.Id }) |
                    @Html.ActionLink("Esita", "ChangeState", new { id = item.Id, state = 2 })
                </td>
            }
            else if (
                (item.State == 2) && (User.IsInRole("Osakonnajuhataja")) 
               // || (item.State == 2) && (item.Person.Email == User.Identity.Name)
                )
            {
                <td>
                    @Html.ActionLink("Teave", "Details", new { id = item.Id }) |
                    @Html.ActionLink("Kinnita", "ChangeState", new { id = item.Id, state = 3 }) |
                    @Html.ActionLink("Lükka tagasi", "ChangeState", new { id = item.Id, state = 1 })
                </td>
            }
            else if ((item.State == 3) && (User.IsInRole("Raamatupidaja")))
            {
                <td>
                    @Html.ActionLink("Teave", "Details", new { id = item.Id }) |
                    @Html.ActionLink("Hüvita reis", "ChangeState", new { id = item.Id, state = 4 })
                </td>
            }
            else
            {
                <td>
                    @Html.ActionLink("Teave", "Details", new { id = item.Id })
                </td>
            }

        </tr>
    }

</table>